meta-zephyr-sdk: Add separate QEMU recipe for ARC
This commit makes the following changes to add a separate QEMU recipe
for ARC.

1. Re-generate "cross.patch" as there're quite some changes in the
   newer "configure" script.

2. Remove "--disable-sheepdog" as otherwise configurations fails with
   --------------->8------------
   ERROR: unknown option --disable-sheepdog
   --------------->8------------

3. Add symlinks to the ARC QEMU emulator executables in `/usr/bin`.

Co-authored-by: Stephanos Ioannidis <root@stephanos.io>
Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>