ci: Exclude C++ sample and test builds on non-Linux hosts
This commit updates the CI workflow such that Zephyr C++ samples and
tests are only built on Linux hosts because there is a known issue
causing the following link error using non-Linux toolchains:

  undefined reference to `_impure_ptr'

Revert this when the GitHub issue #760 is fixed.

Signed-off-by: Stephanos Ioannidis <root@stephanos.io>